### ISSUE TITLE
貌似视频播放不完整

### ISSUE THREAD

**Issue by kejiefu** [hauk0101/video-hls-encrypt#1]
貌似视频播放不完整，我上传了个4分钟的视频，才播放了48秒而已，是不是还要设置下什么东西的

**Comment by kejiefu** [comment]
我发现40多秒的视频的话，还是可以播放完整的

**Comment by kejiefu** [comment]
> 貌似视频播放不完整，我上传了个4分钟的视频，才播放了48秒而已，是不是还要设置下什么东西的

**Comment by hauk0101** [comment]
有报错吗？或是代码截图之类的。
