### ISSUE TITLE
输入需要播放的视频名称写什么路径？

### ISSUE THREAD

**Issue by blackyhb** [hauk0101/video-hls-encrypt#10]
输入需要播放的视频名称写什么路径？转码后的m3u8文件名吗？需要带端口和其他文件的路径吗？

**Comment by hauk0101** [comment]
不需要写路径和端口，只需要写你上传时候的文件名即可。
其实，你也可以看一下处理逻辑的代码，很简单的，甚至也可以按自己需求进行改造。
