### ISSUE TITLE
解密播放时长变短

### ISSUE THREAD

**Issue by weifeng727** [hauk0101/video-hls-encrypt#14]
上传了一个140M的视频，时长4分多钟，但是解密播放起来却只有40秒，好几个视频试过都是这样，有大神解决下吗

**Comment by mirari** [comment]
`.addOption('-hls_list_size', '0')`
ffmpegCommand那段里面加上这一句

**Comment by weifeng727** [comment]
> `.addOption('-hls_list_size', '0')`
> ffmpegCommand那段里面加上这一句

虽然我先找到解决办法了，但还是得谢谢你 (*￣︶￣)

**Comment by hauk0101** [comment]
这块更多的依赖的是 ffmpeg 库的api，如果对视频有特殊定制化处理，可以去搜索查看 ffmpeg 相关的内容。
