### ISSUE TITLE
无法使用videojs播放

### ISSUE THREAD

**Issue by 2016011969sunyifang** [hauk0101/video-hls-encrypt#18]
大佬 本地播放可以 我引用服务器（.net 跑mmpeg加密）的资源使用videojs播放  获取分片成功但是大小都为0这是因为什么

**Comment by hauk0101** [comment]
你可以看看切片完之后，在服务器上的文件大小是多少，看描述像是在服务器上切的过程有问题

**Comment by 2016011969sunyifang** [comment]
> 你可以看看切片完之后，在服务器上的文件大小是多少，看描述像是在服务器上切的过程有问题

但是有一个问题 我把视频链接放到一些m3u8视频播放器上是可以播放的
最后通过直接调用hls.js成功了 没找到失败原因

**Comment by hauk0101** [comment]
那就是 video.js 需要配合 hls.js 一起用的，单纯的 video.js 没法解析 m3u8 的文件

**Comment by 2016011969sunyifang** [comment]
> 那就是 video.js 需要配合 hls.js 一起用的，单纯的 video.js 没法解析 m3u8 的文件

我记得好像在哪个版本吧videojs加进去了

**Comment by 2016011969sunyifang** [comment]
> > 那就是 video.js 需要配合 hls.js 一起用的，单纯的 video.js 没法解析 m3u8 的文件
> 
> 我记得好像在哪个版本吧videojs加进去了

hls   还是我看错
不过现在项目vite的 webpack还没配置 好像用不了那个包  等以后弄了再改吧
谢谢了大佬

**Comment by 2016011969sunyifang** [comment]
> 那就是 video.js 需要配合 hls.js 一起用的，单纯的 video.js 没法解析 m3u8 的文件

大佬加个联系方式？有空探讨下videojs
sunyifang535          wx
