### ISSUE TITLE
还有些问题，想请教下你

### ISSUE THREAD

**Issue by kejiefu** [hauk0101/video-hls-encrypt#2]
可以加下QQ详细问下么，谢谢了

**Comment by hauk0101** [comment]
发我E-mail吧，或者就在这里提问，也方便后面如果有人遇到相似的问题，大家一起讨论。

**Comment by kejiefu** [comment]
视频的加密好像并没有效果，我去掉加密之后，好像一样能读出来，而且还有个问题，就是视频太大的话，视频会丢失一部分，我看了下m3u8文件，发现不是从0开始播放的

**Comment by hauk0101** [comment]
@kejiefu 
1. 我这里只是对 .key 秘钥文件做了保护，如果你的 .key 文件没有限制访问，那么肯定是可以正常访问的。
2. 不是从0播放的，你可以看一下你转码时候是否有限制？播放的时候是否有跳播？
3. 视频丢失一部分的情况，是否是在转码时发生了错误，导致了某部分没有正常被切片呢？
4. 其实我的这个项目仅仅是为大家提供一种视频加密的思路，并不能算是比较成熟的视频加密方案，还是建议你根据你们的实际情况，和此功能相关的同事深入探讨下，如何制定一个更符合你们需求的方案。
