### ISSUE TITLE
FFMPEG的save函数没权限

### ISSUE THREAD

**Issue by Lamsio** [hauk0101/video-hls-encrypt#20]
当跑到save函数那段时报错，提示没权限，无法生成ts和m3u8，想问一下作者有什么办法解决吗？
我尝试用管理员权限，但依旧显示没权限

**Comment by hauk0101** [comment]
你先试试不用代码的方式跑，直接参考 ffmpeg 的命令方式跑，同时注意下你安装的 ffmpeg 的版本，不确定是不是最新版本导致命令变化
