### ISSUE TITLE
请教两个问题 1.怎么在ipfs上用这个项目？ 2.音频文件是否也可以用此项目来加密呢？

### ISSUE THREAD

**Issue by asleep2** [hauk0101/video-hls-encrypt#3]

**Comment by hauk0101** [comment]
@asleep2 
1.抱歉，本人没有研究过ipfs技术，但是可以给你一些建议：因为我的这个项目的加密本质是基于hls协议的，也就是说如果你这边用的ipfs的播放器，能够支持播放 m3u8/ts文件的话，可能是可以正常使用，只不过可能你不能用本项目中的videojs.hls.js 库去解析你们的 hls 协议文件。
2.音频文件原则上应该是可以，不过在使用 ffmpeg 进行转码时，应该注意转码源和目标源的格式要与你的音频文件的编码格式对应（不是文件后缀），之后同理，需要你的播放器能够正常解析转码后的流媒体文件。

**Comment by asleep2** [comment]
> @ asleep2
> 1.抱歉，本人没有研究过ipfs技术，但是可以给你一些建议：因为我的这个项目的加密本质是基于hls协议的，也就是说如果你这边用的ipfs的播放器，能够支持播放m3u8 / ts文件的话，可能是可以正常使用，只不过可能你不能用本项目中的videojs.hls.js库去解析你们的hls协议文件
> .2。音频文件原则上应该是可以，不过在使用ffmpeg进行转码时，应该注意转码源和目标源的格式要与你的音频文件的编码格式对应（不是文件后缀），之后同理，需要你的播放器能够正常解析转码后的流媒体文件。

重复＃

**Comment by asleep2** [comment]
感谢你的回复。用ipfs主要是考虑到价钱：我有将近50多GB的文件，走服务器流量恐怕有些吃不消，而其他方案我暂且还不知道。

现在我找到了这个视频https://youtu.be/xQNjK3BC2CA
我想ipfs应该是可以用的，你能看看吗？本人技术小白。

**Comment by hauk0101** [comment]
抱歉，这块真不是很了解，也不知道是否能有答案，建议可以在国外网站多搜集些相关资料

**Comment by asleep2** [comment]
> 抱歉，这块真不是很了解，也不知道是否能有答案，建议可以在国外网站多搜集些相关资料
请问该项目能否不转码，不切片，只加密？？

**Comment by hauk0101** [comment]
@asleep2  那你就针对你的文件做处理就好了啊，比如你的 demo.mp4 文件，你在访问它的时候，就像我保护项目里的 .key 文件一样做一些访问限制。

**Comment by asleep2** [comment]
@hauk0101  不会弄啊，还是请写个教程或者傻瓜包之类的吧

**Comment by hauk0101** [comment]
@asleep2 最近没有时间，等有时间的时候，我考虑下吧。
