### ISSUE TITLE
请问到这一步后该怎么做？

### ISSUE THREAD

**Issue by asleep2** [hauk0101/video-hls-encrypt#4]
![fhian](https://user-images.githubusercontent.com/39230916/45917253-aca25080-bea5-11e8-96cc-b4e454ea6e10.PNG)

**Comment by asleep2** [comment]
哈哈，成了！ 但为啥三分钟的视频最后出来的只有43秒？晕啊

**Comment by hauk0101** [comment]
@asleep2 你可以看下切片的时候是否不全

**Comment by lzhaoyang** [comment]
ffmpeg做切片的时候如果不加 -hls_list_size = 0，默认只会有最后的五个切片，如果这个参数设置为0，那么就是把所有的切片列表写入这个文件的

**Comment by fireinrain** [comment]
@asleep2 ffmpeg做切片的时候如果不加 -hls_list_size = 0，默认只会有最后的五个切片，如果这个参数设置为0，那么就是把所有的切片列表写入这个文件的

**Comment by mirari** [comment]
> @asleep2 ffmpeg做切片的时候如果不加 -hls_list_size = 0，默认只会有最后的五个切片，如果这个参数设置为0，那么就是把所有的切片列表写入这个文件的

幸好看到你的回复。我尝试了这个demo，发现m3u8里的列表总是只有最后那一截，原来是这个缘故
