### ISSUE TITLE
嗨，我找到了一个切片处理视频的帖子，感觉跟你的项目原理相似。

### ISSUE THREAD

**Issue by asleep2** [hauk0101/video-hls-encrypt#5]
在这里 https://www.hostloc.com/thread-438344-1-1.html

我在电脑上试了一下，确实在本地上用播放器“无法播放”。
![jyj](https://user-images.githubusercontent.com/39230916/47630437-c1949280-db7b-11e8-8aa6-37a505aa7943.PNG)

现在我想看最终的效果，请问是不是得做一个网页才行啊？

**Comment by hauk0101** [comment]
@asleep2 
我看了下这个帖子，我个人理解如下：
首先，我们其实本质用的都是FFmpeg这个开源库，来做的视频处理；
其次，我和他的侧重点不一样，我对他那个帖子的理解，更多的他可能侧重于如何把通过视频ffmpeg把视频加密结果做出来，然后能够播放即可，应该是为大家提供一个使用原理；
然而，我的侧重点是从原始视频，到加密处理，到后台策略，再返回至普通用户能够观看，这么相对较完整的一套流程。

所以，我其实不太明白，你说的看最终效果是要看什么效果呢，
如果只是看 ffmpeg 是否能正常加密/解密，我觉得可以更多的去从 ffmpeg 方向入手。
如果是想从整套流程的把控和输出解决方案来讲，我觉得可以参考我的Demo 。
