### ISSUE TITLE
每一个分片都需要请求一个key吗

### ISSUE THREAD

**Issue by fireinrain** [hauk0101/video-hls-encrypt#8]
你好，谢谢你做的这个demo。我尝试了一下，有两个问题想请教一下：
1. 我查看浏览器的devtools 的network，每次请求一个分片就会请求一个key，这样感觉会有非常多的请求。
是否可以只请求一次key，然后每次取得分片只使用这一个key来播放呢？
2. 如果每次请求到一个key来解码一个分片，是否可以做到动态的key呢？也就是每一片的key是不一样的。
我搜索过一些答案，基本都是固定的key。

**Comment by hauk0101** [comment]
@lzhaoyang 
你好，关于分片请求key文件的频率，其实原理是mmpeg库提供的加密解密方案，本身来说我并没有刻意去控制它的请求频率。
当然，我也没有深入去了解mmpeg的相关API，你可以通过去尝试深入了解mmpeg的相关API看看是否能够实现你想要的结果，包括key文件的请求频率，以及动态key的实现等等。

**Comment by fireinrain** [comment]
我找了一下最新版本的ffmpeg在命令行加入这个参数-hls_flags periodic_rekey ,同时保证key_info.key中的秘钥文件地址是一直变动的，那么在ffmpeg切片切到下一片的时候那么它会去重新读取info中指定的key文件地址中的内容，这样的话只要事先指定一个key的集合，然后写个程序保持key_info.key文件中的内容是变化的，那么就可以做到每一片都是可以不一样的key

**Comment by hauk0101** [comment]
@lzhaoyang good job，是这么个思路。

**Comment by huangkai4966** [comment]
> 你好，谢谢你做的这个demo。我尝试了一下，有两个问题想请教一下：
> 
> 1. 我查看浏览器的devtools 的network，每次请求一个分片就会请求一个key，这样感觉会有非常多的请求。
>    是否可以只请求一次key，然后每次取得分片只使用这一个key来播放呢？
> 2. 如果每次请求到一个key来解码一个分片，是否可以做到动态的key呢？也就是每一片的key是不一样的。
>    我搜索过一些答案，基本都是固定的key。

你好,我现在也遇到了和你提出的第1条相同的问题,并且查询hls协议和mmpeg的参数也没能找到答案.请问你这边是否解决了关于控制切片ts访问key频率的方法呢,谢谢.
