### ISSUE TITLE
nginx-vod-module + hls.js 可以实现类似功能

### ISSUE THREAD

**Issue by wnpllrzodiac** [hauk0101/video-hls-encrypt#9]
简单的修改就可以做到 encrypt on the fly, 不需要切片生成ts文件。配合CDN的分发，架构比较简单。hls.js 也只需要简单的修改。有兴趣的可以交流下。

**Comment by hauk0101** [comment]
@wnpllrzodiac  个人理解哈，
1、你说的这种应该是直播流了吧，nginx-vod-module + CDN 是在服务端做的类似实时流媒体处理，hls.js 是用来客户端处理流媒体的。
2、我这个其实还没有涉及到直播，就是一个普通的播放，切片的作用有两个，一个是降低单个文件的下载速率受带宽的影响，从而给客户造成不好的体验；二是在通过FFmpeg本身，对切片流的加密，做的示例。

综上，我觉得咱俩可能是在两个方向的吧，并不冲突，不过也可能我理解的不对，因为针对直播流这块，确实还没有较深入的研究。
另外，针对CDN，其实很多CDN服务商本身也提供静态流媒体存储对象的切片服务，但其实他们底层用的切片，还是FFmpeg，所以我这其实也只是想让喜欢折腾的朋友，多了解一点皮毛，抛砖引玉吧。毕竟一般的视频服务公司，没有自己的CDN集群的话，直接去搞FFmpeg，转码延时就是一个坎，倒不如直接花钱买服务。

**Comment by wnpllrzodiac** [comment]
nginx vod 是点播视频切片的，直播也也部分功能支持。

**Comment by LONGxianfu222** [comment]
> nginx vod是点播视频切片的，直播也也部分功能支持。

作者大大研究出来了吗。是否可以做到在网页观看直播的时候倍速播放，或者加速播放

**Comment by hauk0101** [comment]
@wnpllrzodiac 
> nginx vod 是点播视频切片的，直播也也部分功能支持。

嗯，如果是做点播的话，其实你的这种思路就是直接通过服务端进行加密处理了，也是一种思路，不过我没有在这一块做深入研究。
咱们的路子其实就不一样了，不过适合自己的才是最好的，要是你能针对你的解决方案做一个原理梳理和示例，则是更好不过了呢。

**Comment by hauk0101** [comment]
@LONGxianfu222 
直播还允许倍速播放吗？这个需求有点奇怪了。比较直播的延时都是一个挺让人头疼的问题了。

**Comment by LONGxianfu222** [comment]
> @LONGxianfu222
> 直播还允许倍速播放吗？这个需求有点奇怪了。比较直播的延时都是一个挺让人头疼的问题了。

是可以用油猴插件写入一些脚本实现的

**Comment by LONGxianfu222** [comment]
> @LONGxianfu222
> 直播还允许倍速播放吗？这个需求有点奇怪了。比较直播的延时都是一个挺让人头疼的问题了。

大概就是用网页观看直播时用倍速播放，达到去延时的效果。流媒体如果流完时会造成卡顿，如果倍速播放调成1.1或者1.01-1.09这样非常低的情况应该能减少卡顿的次数，达到延时消除的效果吧

**Comment by LONGxianfu222** [comment]
> @LONGxianfu222
> 直播还允许倍速播放吗？这个需求有点奇怪了。比较直播的延时都是一个挺让人头疼的问题了。

网页看直播能否实现倍速播放。

**Comment by hauk0101** [comment]
@LONGxianfu222 
个人理解，针对直播来说，所谓的减少延迟，分为两个部分吧，一个是客户端的网速占用，通过软件或人为的手段，来为观看直播的软件提供足够的网速。另一个是服务器端，通过服务器分发或是增加自身带宽，来减少延迟。
但是需要注意的是，针对上述两种情况，就直播本身而言，并没有所谓的“倍速播放”。

所谓的“倍速播放”的意思是，当前这个多媒体视频源，已经完全录制完成，此时再客户端通过倍速控制来实现的倍速播放。这个已经完成录制的视频源，可以被称为点播，或是回播。

毕竟，作为直播来说，直播源都还不确定有多少时间，你这倍速播放要是超前了，效果该是什么样呢？所以，这个是个很奇怪的逻辑。举个例子，某主播在7:00-8:00直播内容，你在7:15的时候，进行倍速播放。此时7:15的主播端的摄像头是正常的时间，而客户端由于有“倍速播放”，已经播放到了7:20，此时客户端的内容从哪里来呢？

再者，先不说“倍速播放”，就是在直播的过程中，连快进拖拽都不可能实现，就别说“倍速播放”了。

综上，可能你说的直播和我理解的直播有出入吧，有些跑偏了。
